name: Sitemapper CI

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"
  schedule:
    - cron: "0 0 * * MON"

jobs:
  check_format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - latest
        experimental:
          - false
        include:
          - crystal_version: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal_version }}-alpine
    steps:
      - uses: actions/checkout@v1
      - name: Set up Crystal cache
        uses: actions/cache@v2
        id: crystal-cache
        with:
          path: |
            ~/.cache/crystal
            bin/ameba
            lib
          key: ${{ runner.os }}-crystal-${{ matrix.crystal_version }}-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-crystal-${{ matrix.crystal_version }}
      - name: Install shards
        if: steps.crystal-cache.outputs.cache-hit != 'true'
        run: shards check || shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba

  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - latest
        experimental:
          - false
        include:
          - crystal_version: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal_version }}-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Set up Crystal cache
        uses: actions/cache@v2
        id: crystal-cache
        with:
          path: |
            ~/.cache/crystal
            bin/ameba
            lib
          key: ${{ runner.os }}-crystal-${{ matrix.crystal_version }}-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-crystal-${{ matrix.crystal_version }}
      - name: Install shards
        if: steps.crystal-cache.outputs.cache-hit != 'true'
        run: shards check || shards install
      - name: Run tests
        run: crystal spec
