name: Sitemapper CI

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      matrix:
        container:
          - crystallang/crystal:latest-alpine
          - crystallang/crystal:nightly-alpine
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Cache Crystal
        uses: actions/cache@v1
        with:
          path: ~/.cache/crystal
          key: ${{ runner.os }}-${{ matrix.container }}-crystal
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba

  specs:
    strategy:
      matrix:
        container:
          - crystallang/crystal:latest-alpine
          - crystallang/crystal:nightly-alpine
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Cache Crystal
        uses: actions/cache@v1
        with:
          path: ~/.cache/crystal
          key: ${{ runner.os }}-${{ matrix.container }}-crystal
      - name: Run tests
        run: crystal spec
